#include "../../constjson.hpp"

#include <iostream>

constexpr const char cppconfig[] = R"(
  {
  "configuration": {
    "name": "Linux",
    "intelliSenseMode": "linux-clang-x64",
    "compilerPath": "/usr/bin/clang++-16",
    "cStandard": "c17",
    "cppStandard": "c++20",
    "includePath": [
      "/usr/local/boost_1_80_0/",
      "/home/gkxx/exercises/small_exercises/"
    ],
    "compilerArgs": [
      "-Wall",
      "-Wpedantic",
      "-Wextra"
    ]
  },
  "version": 4
}
)";

constexpr const char tasks[] = R"(
  {
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: g++-12 build active file",
            "command": "/usr/bin/g++-12",
            "args": [
                "-fdiagnostics-color=always",
                "-g",
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}",
                "-std=c++20"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        }
    ],
    "version": "2.0.0"
}
)";

int main() {
  using namespace gkxx::constjson;

  using empty_object = parse<"{}">::result;
  std::cout << pretty_type_name<empty_object>() << std::endl;

  using array = parse<"[\"a\", \"b\"]">::result;
  std::cout << pretty_type_name<array>() << std::endl;

  using cppconfig_result = parse<cppconfig>::result;
  std::cout << pretty_type_name<cppconfig_result>() << std::endl;

  using tasks_result = parse<tasks>::result;
  std::cout << pretty_type_name<tasks_result>() << std::endl;
  return 0;
}